name: Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '19'
      - uses: google/wireit@setup-github-actions-caching/v1
      - run: npm install
      - run: npm run test
