name: Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          tag_name: ${{ github.ref }}
          prerelease: true
          draft: true
          files: |
            generated/openapi.json
            generated/openapi.dereferenced.json
            generated/openapi.3.0.json
            generated/openapi.dereferenced.3.0.json
